<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVjy9whq\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVjy9whq/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVjy9whq.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVjy9whq\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVjy9whq\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Vjy9whq',
    'container.build_id' => 'cfa89929',
    'container.build_time' => 1515168417,
));
